name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 0.1.0
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
