name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 2.7.3
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.2.1
  tiledjsonreader: ^1.2.4
  http: ^0.13.4
  a_star_algorithm: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
