name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 0.2.2
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.19.1
  ordered_set: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
