name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 0.6.7
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.22.0
  tiledjsonreader: ^0.0.5

dev_dependencies:
  test: any

flutter:

  uses-material-design: true
