name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 0.6.19
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.25.0
  ordered_set: ^2.0.0
  tiledjsonreader: ^0.0.7

dev_dependencies:
  test: any

flutter:

  uses-material-design: true
